# Config file for automatic testing at travis-ci.org

language: python
# http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
  - "pypy3"
  - "pypy"

#before_install:
  #- pip install -U pip

install:
  - pip install -U -r dev-requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install ordereddict; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.2 ]]; then pip install -U virtualenv<14.0.0; fi

before_script:
  - flake8 .

script: PYTHONPATH=. py.test tests  # is setting PYTHONPATH the right thing to do?
